services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
